
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev-challenges?autoReconnect=true&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    server:
      port:8080
